epochs: 10
test_steps: 1000
repeats: 1
envs:
  - CartPole-v0
algorithms:
  -
    name: DQN
    type: DQN
    train_steps: 10000
    config:
      discount: 0.95
      epsilon:
        from_: 1.0
        offset: 1000
        over: 50000
        test: 0.0
        to: 0.05
      frame_skip: 1
      history: 4
      noop_max: 5
      initial_learning_rate: 1e-3
      network: network_control
      replay_capacity: 1000
      start_learning: 1000
      sync_target: 50
      batch_size: 128
