experiment: doom
epochs: 100
test_steps: 1e4
repeats: 3
envs:
  - SimpleDeathmatch-v0
  - SimpleGather-v0
algorithms:
  -
    name: A3C
    type: A3C
    train_steps: 8e5
    initial_learning_rate: 2e-5
    frame_skip: 4
  -
    name: DQN
    type: DQN
    train_steps: 2e5
    initial_learning_rate: 2e-5
    batch_size: 32
    frame_skip: 4
